// создание новых счетов
POST http://localhost:8080/account
Content-Type: application/json

{"owner": "Lars von Trier", "number": "+7(911)111-11-11","volume": 100000}

###
POST http://localhost:8080/account
Content-Type: application/json

{"owner": "Lars von Trier", "number": "+7(911)111-11-11","volume": 50000}

###
POST http://localhost:8080/account
Content-Type: application/json

{"owner": "Lars von Trier", "number": "+7(911)111-11-11","volume": 25000}

###
POST http://localhost:8080/account
Content-Type: application/json

{"owner": "Christoph Waltz", "number": "+7(922)222-22-22","volume": 20000}

###
POST http://localhost:8080/account
Content-Type: application/json

{"owner": "Stellan Skarsgard", "number": "+7(933)333-33-33","volume": 20000}

###
POST http://localhost:8080/account
Content-Type: application/json

{"owner": "Mads Mikkelsen", "number": "+7(944)444-44-44","volume": 1000000}

###
// создание новых типов кэшбека
POST http://localhost:8080/cashback
Content-Type: application/json

{"cat": "regional", "perc": 10}

###
POST http://localhost:8080/cashback
Content-Type: application/json

{"cat": "national", "perc": 20}

###
POST http://localhost:8080/cashback
Content-Type: application/json

{"cat": "VIP", "perc": 21}

###
// Просмотр всех счетов
GET http://localhost:8080/accounts

###
// Просмотр всех типов кэшбеков
GET http://localhost:8080/cashbacks

###
// Получить конкретный счет, например, Мадса Миккельсена
GET http://localhost:8080/account/900fc77d-a17d-40c8-b669-01fac999d73b

###
// Выдать список счетов другого пользователя приложения (Ларс фон Триер)
GET http://localhost:8080/person/+7(911)111-11-11

###
// Выдать список СВОИХ счетов (Ларс фон Триер)
GET http://localhost:8080/own/+7(911)111-11-11

###
// Положить деньги на счет (Кристоф Вальц)
PUT http://localhost:8080/account/operation
Content-Type: application/json

{"id": "1f307984-da60-41ff-a4c2-be9d30c85d1b", "add": 3000}

###
// Снять деньги со счета (Мадс Миккельсен)
PUT http://localhost:8080/account/operation
Content-Type: application/json

{"id": "900fc77d-a17d-40c8-b669-01fac999d73b", "subtr": 500000}

###
// Перевод денег, например, от Стеллана Скарсгарда Мадсу Миккельсену
// ШАГ 1 - узнаем счета Стеллана
GET http://localhost:8080/own/+7(933)333-33-33

###
// ШАГ 2 - узнаем счета Мадса
GET http://localhost:8080/person/+7(944)444-44-44

###
// ШАГ 3 - осуществим международный перевод (с кэшбеком)
PUT http://localhost:8080/account/operation
Content-Type: application/json

{"from_id": "ddd402ee-2993-4e00-a2f5-74228ee7bef6", "to_id": "900fc77d-a17d-40c8-b669-01fac999d73b", "cat": "national", "summa": 2525}

###
// Осуществим перевод с одного счета Ларса фон Триера на другой его счет
// ШАГ 1  - выдать список СВОИХ счетов
GET http://localhost:8080/own/+7(911)111-11-11

###
// ШАГ 2 - осуществим перевод (БЕЗ КЭШБЕКА)
PUT http://localhost:8080/account/operation
Content-Type: application/json

{"from_id": "f07cc553-d819-452e-8920-e87040317b57", "to_id": "80197568-b868-40bb-8178-fe73b85680cd", "cat": null, "summa": 2500}
###
// Осуществим заранее невозможный перевод с одного счета Ларса фон Триера на другой его счет
// Причина - мало средств на отправном счету
// ШАГ 1  - выдать список СВОИХ счетов
GET http://localhost:8080/own/+7(911)111-11-11

###
// ШАГ 2 - попытаемся осуществить перевод (БЕЗ КЭШБЕКА)
PUT http://localhost:8080/account/operation
Content-Type: application/json

{"from_id": "bb03c8ec-d498-4a18-876f-35dc1b7eaeed", "to_id": "80197568-b868-40bb-8178-fe73b85680cd", "cat": null, "summa": 250000}