###
POST localhost:8071/create/1/0

###
POST localhost:8071/create/2/100

###
POST localhost:8071/update/1/5000

###
POST localhost:8071/update/2/234

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 1,
  "destinationId": 2,
  "value": 234
}

###
GET localhost:8071/balance/1

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 1,
  "destinationId": 2,
  "value": 1501
}

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 1,
  "destinationId": 2,
  "value": 1000,
  "category": "gold"
}

###
GET localhost:8071/get_cashback/1